#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# file_name.py
# Python 3.7
"""
Created on Wed Apr 24 10:36:50 2019

@author: pedro brodude
Modified:  Wed Apr 24 10:36:50 2019
Description
____________________

"""

import numpy as np
import matplotlib.pyplot as plt

