#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# file_name.py
# Python 3.7
"""
Created on Thu Mar  7 12:38:43 2019

@author: pedro brodude
Modified:  Thu Mar  7 12:38:43 2019
Description
____________________

"""

import numpy as np
import matplotlib.pyplot as plt

# simple_plot_with_error_bars.py

import numpy as np, matplotlib.pyplot as plt

num_points = 5

x_min, x_max = 0, 4

x_values = np.linspace(x_min, x_max, num_points)

y_values = x_values**2

#errors
x_errors = [0.1, 0.1, 0.1, 0.1, 0.1]
y_errors = [1.8, 3.9, 2.8, 2.5, 2.3]


#plt.plot(x_values,y_values)
plt.errorbar(x_values, y_values, yerr=y_errors, xerr = x_errors, capsize=7)


