#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# file_name.py
# Python 3.7
"""
Created on Thu May  2 17:29:59 2019

@author: pedro brodude
Modified:  Thu May  2 17:29:59 2019
Description
____________________

"""

import numpy as np
import matplotlib.pyplot as plt

x_equation = np.linspace(0,10,100)
y_equation = np.sin(x_equation)      # of course this is actually very long and messy

plt.plot(x_equation,y_equation)
plt.text(y_equation)